"""HIGH_VALUE_TASKS 扩展包：补齐网络、状态、数据、媒体、后台等 App 级任务卡片。

与 build_index_v3.py 中 HIGH_VALUE_TASKS 的 schema 完全一致。
通过 build_index_v3.HIGH_VALUE_TASKS.extend(HIGH_VALUE_TASKS_EXT) 接入。

覆盖 P0 冒烟测试发现的空白：
- 网络：WebSocket 长连接、上传下载带进度、网络连通性检测
- 状态：@State / @Link / @Provide / @Observed 响应式
- 数据：Preferences 偏好、沙盒 JSON 读写
- 媒体：相机拍照、视频播放、录音、扫码、图库选取
- 后台/推送：Push、后台任务
- 安全：生物识别、Keystore 加密存储
- UI 交互：Toast、Loading、ActionMenu、长按菜单、手势
- 布局：MediaQuery 响应式、画中画、Canvas
- 工程：国际化、深色模式
"""

from __future__ import annotations

HIGH_VALUE_TASKS_EXT: list[dict] = [
    {
        "task_id": "network.websocket.basic",
        "title": "WebSocket 长连接",
        "aliases": ["WebSocket 通信", "长连接", "实时消息"],
        "intent": "建立 WebSocket 连接收发实时消息，处理断线重连与心跳。",
        "when_to_use": ["实时聊天 / IM", "推送服务器消息", "长连接保持"],
        "recommended_apis": ["stdx.net.websocket"],
        "optional_apis": ["std.time"],
        "path_keywords": ["net_websocket", "WebSocket"],
        "example_keywords": ["WebSocket 客户端", "upgradeFromClient"],
        "tags": ["network", "websocket", "stdx"],
    },
    {
        "task_id": "network.upload.progress",
        "title": "带进度的文件上传",
        "aliases": ["文件上传", "上传进度", "request upload"],
        "intent": "通过 RequestAgent 上传文件并监听上传进度。",
        "when_to_use": ["上传图片 / 视频到服务器", "需要进度条反馈"],
        "recommended_apis": ["arkui.request_agent"],
        "optional_apis": ["arkui.progress", "arkui.canvas_context_2d"],
        "path_keywords": ["cj-apis-request", "RequestAgent", "上传下载"],
        "example_keywords": ["上传文件", "uploadFile", "onProgress"],
        "tags": ["network", "upload", "request"],
    },
    {
        "task_id": "network.download.background",
        "title": "后台下载大文件",
        "aliases": ["文件下载", "后台下载", "断点续传"],
        "intent": "使用 RequestAgent 发起可在后台完成的长时间下载任务。",
        "when_to_use": ["下载大文件", "应用退后台仍需下载", "断点续传"],
        "recommended_apis": ["arkui.request_agent"],
        "optional_apis": [],
        "path_keywords": ["cj-apis-request", "后台下载", "long-running"],
        "example_keywords": ["后台下载", "request.downloadFile"],
        "tags": ["network", "download", "background"],
    },
    {
        "task_id": "network.connectivity.detect",
        "title": "检测网络连通性",
        "aliases": ["网络检测", "联网状态", "connection state"],
        "intent": "判断设备是否联网及网络类型，监听网络变化事件。",
        "when_to_use": ["首屏网络判断", "离线提示", "Wi-Fi / 移动网络切换"],
        "recommended_apis": ["harmonyos.net.connection"],
        "optional_apis": [],
        "path_keywords": ["NetworkKit", "网络连接", "NetConnection", "netHandle"],
        "example_keywords": ["网络连接", "onNetConnected"],
        "tags": ["network", "connectivity"],
    },
    {
        "task_id": "network.http.headers",
        "title": "HTTP 请求自定义 Header 和 UA",
        "aliases": ["修改 UA", "自定义 Header", "User-Agent"],
        "intent": "发起 HTTP 请求时设置 headers / UA 并按需携带 Cookie。",
        "when_to_use": ["调三方需特定 UA 的接口", "鉴权 token 放 header", "带 Cookie 请求"],
        "recommended_apis": ["arkui.http_request"],
        "optional_apis": [],
        "path_keywords": ["cj-apis-net-http", "requestInStream", "http.request"],
        "example_keywords": ["HTTP 请求", "自定义 Header"],
        "tags": ["network", "http"],
    },
    {
        "task_id": "state.at_state.basic",
        "title": "@State 基础响应式",
        "aliases": ["@State 装饰器", "组件内响应式", "state 变量"],
        "intent": "用 @State 声明组件内状态变量，改值后自动触发 UI 刷新。",
        "when_to_use": ["按钮点击改计数器", "表单输入反馈", "列表项选中态"],
        "recommended_apis": ["arkui.state"],
        "optional_apis": [],
        "path_keywords": ["cj-ui-state", "@State", "状态管理"],
        "example_keywords": ["@State 示例", "state 变量"],
        "tags": ["state", "arkui"],
    },
    {
        "task_id": "state.at_link.two_way",
        "title": "@Link 父子组件双向绑定",
        "aliases": ["@Link 装饰器", "双向绑定"],
        "intent": "在父子组件之间通过 @Link 实现状态的双向同步。",
        "when_to_use": ["子组件修改父组件状态", "复用表单输入子组件"],
        "recommended_apis": ["arkui.state"],
        "optional_apis": [],
        "path_keywords": ["cj-ui-state", "@Link"],
        "example_keywords": ["@Link 示例", "双向绑定"],
        "tags": ["state", "arkui"],
    },
    {
        "task_id": "state.provide_consume.cross_layer",
        "title": "@Provide / @Consume 跨层传递",
        "aliases": ["@Provide", "@Consume", "跨层状态"],
        "intent": "祖先组件用 @Provide 广播，深层后代用 @Consume 订阅。",
        "when_to_use": ["主题切换跨层同步", "深层组件订阅用户信息"],
        "recommended_apis": ["arkui.state"],
        "optional_apis": [],
        "path_keywords": ["cj-ui-state", "@Provide", "@Consume"],
        "example_keywords": ["@Provide", "跨层通信"],
        "tags": ["state", "arkui"],
    },
    {
        "task_id": "state.observed_objectlink.object",
        "title": "@Observed / @ObjectLink 对象响应",
        "aliases": ["@Observed", "@ObjectLink", "对象响应式"],
        "intent": "让对象字段变化也能触发 UI 刷新（State 只对引用变化响应）。",
        "when_to_use": ["state 是对象需要改字段也刷 UI", "嵌套数据模型"],
        "recommended_apis": ["arkui.state"],
        "optional_apis": [],
        "path_keywords": ["cj-ui-state", "@Observed", "@ObjectLink"],
        "example_keywords": ["@Observed", "ObjectLink 示例"],
        "tags": ["state", "arkui"],
    },
    {
        "task_id": "state.localstorage.persist",
        "title": "LocalStorage 持久化状态",
        "aliases": ["LocalStorage", "本地状态"],
        "intent": "将 @StorageProp / @StorageLink 关联到 LocalStorage 做跨页面状态共享。",
        "when_to_use": ["多个 Page 共享状态", "状态生命周期跨页面"],
        "recommended_apis": ["arkui.localstorage"],
        "optional_apis": ["arkui.state"],
        "path_keywords": ["cj-ui-state", "LocalStorage"],
        "example_keywords": ["LocalStorage 示例", "@StorageLink"],
        "tags": ["state", "storage"],
    },
    {
        "task_id": "data.preferences.basic",
        "title": "Preferences 偏好持久化",
        "aliases": ["Preferences", "SharedPreferences", "偏好存储"],
        "intent": "用键值对方式持久化用户偏好、轻量配置。",
        "when_to_use": ["保存用户设置", "主题 / 语言选择", "首次启动标记"],
        "recommended_apis": ["harmonyos.data.preferences"],
        "optional_apis": [],
        "path_keywords": ["ohos_preferences", "Preferences", "getPreferences"],
        "example_keywords": ["preferences.put", "preferences.get"],
        "tags": ["data", "preferences"],
    },
    {
        "task_id": "data.file.sandbox.read_write",
        "title": "沙盒文件读写",
        "aliases": ["文件读写", "应用沙盒", "FileIO"],
        "intent": "在应用沙盒内读写文本 / 二进制文件。",
        "when_to_use": ["缓存 JSON / 日志", "导出用户数据", "读取配置文件"],
        "recommended_apis": ["harmonyos.file.fs"],
        "optional_apis": ["std.fs"],
        "path_keywords": ["CoreFileKit", "fs.open", "fs.write"],
        "example_keywords": ["文件读写", "fs.openSync"],
        "tags": ["file", "fs"],
    },
    {
        "task_id": "data.json.parse_stringify",
        "title": "JSON 解析与序列化",
        "aliases": ["JSON", "JSON 序列化", "JSON 解析"],
        "intent": "把对象序列化成 JSON 字符串或从字符串解析出对象。",
        "when_to_use": ["发 HTTP body", "读写本地配置", "WebSocket 消息格式"],
        "recommended_apis": ["stdx.encoding.json"],
        "optional_apis": [],
        "path_keywords": ["encoding/json", "encoding_json"],
        "example_keywords": ["JsonValue", "JsonElement"],
        "tags": ["data", "json", "stdx"],
    },
    {
        "task_id": "data.picker.file",
        "title": "文件选择器 Picker",
        "aliases": ["文件选择器", "FilePicker", "选文件"],
        "intent": "弹出系统文件选择器让用户挑选文件。",
        "when_to_use": ["上传本地文档 / 图片", "导入数据文件"],
        "recommended_apis": ["arkui.file_picker"],
        "optional_apis": [],
        "path_keywords": ["cj-apis-picker", "FilePicker", "PhotoPicker"],
        "example_keywords": ["FilePicker 示例", "DocumentViewPicker"],
        "tags": ["picker", "file"],
    },
    {
        "task_id": "media.camera.take_photo",
        "title": "相机拍照",
        "aliases": ["拍照", "相机", "CameraKit"],
        "intent": "调起相机拍照并拿到结果图片。",
        "when_to_use": ["头像上传", "扫描识别", "证件拍摄"],
        "recommended_apis": ["harmonyos.camera.kit"],
        "optional_apis": ["harmonyos.image"],
        "path_keywords": ["CameraKit", "camera", "takePicture"],
        "example_keywords": ["拍照示例", "camera.capture"],
        "tags": ["media", "camera"],
    },
    {
        "task_id": "media.video.player",
        "title": "视频播放器",
        "aliases": ["视频播放", "Video 组件", "media player"],
        "intent": "在页面内嵌入视频播放控件，支持播放 / 暂停 / 拖动。",
        "when_to_use": ["本地视频播放", "网络流播放", "短视频内嵌"],
        "recommended_apis": ["arkui.video"],
        "optional_apis": ["harmonyos.media.avplayer"],
        "path_keywords": ["MediaKit", "cj-video", "AVPlayer"],
        "example_keywords": ["视频播放", "avplayer.play"],
        "tags": ["media", "video"],
    },
    {
        "task_id": "media.audio.record",
        "title": "录音",
        "aliases": ["录音", "音频采集", "AudioCapturer"],
        "intent": "采集麦克风音频并保存或做进一步处理。",
        "when_to_use": ["语音输入", "录音功能", "语音识别前置"],
        "recommended_apis": ["harmonyos.media.audio_capturer"],
        "optional_apis": [],
        "path_keywords": ["MediaKit", "audio_capturer", "AudioCapturer"],
        "example_keywords": ["音频采集示例"],
        "tags": ["media", "audio"],
    },
    {
        "task_id": "media.scan.qrcode",
        "title": "扫码识别",
        "aliases": ["扫码", "二维码", "ScanKit"],
        "intent": "调起系统扫码能力识别二维码 / 条形码。",
        "when_to_use": ["扫码登录", "扫码支付", "识别商品码"],
        "recommended_apis": ["harmonyos.scan.kit"],
        "optional_apis": ["harmonyos.camera.kit"],
        "path_keywords": ["ScanKit", "customScan", "scanCodeResult"],
        "example_keywords": ["扫码示例", "scanBarcode"],
        "tags": ["media", "scan"],
    },
    {
        "task_id": "media.gallery.pick",
        "title": "图库选图",
        "aliases": ["相册选图", "图库", "PhotoPicker"],
        "intent": "调起系统图库让用户选图片 / 视频。",
        "when_to_use": ["头像裁剪前选图", "发动态选图", "导入素材"],
        "recommended_apis": ["arkui.file_picker"],
        "optional_apis": ["harmonyos.image"],
        "path_keywords": ["PhotoPicker", "MediaLibraryKit"],
        "example_keywords": ["图库选图", "PhotoViewPicker"],
        "tags": ["media", "picker"],
    },
    {
        "task_id": "notification.push.receive",
        "title": "Push Kit 接收推送",
        "aliases": ["Push", "推送", "远程通知"],
        "intent": "接入 Push Kit 接收远程推送并点击跳转。",
        "when_to_use": ["IM 新消息推送", "活动营销通知"],
        "recommended_apis": ["harmonyos.push.kit"],
        "optional_apis": ["harmonyos.notification"],
        "path_keywords": ["PushKit", "push.getToken", "远程推送"],
        "example_keywords": ["Push Kit 示例", "onNotificationReceived"],
        "tags": ["notification", "push"],
    },
    {
        "task_id": "notification.local.show",
        "title": "本地通知弹出",
        "aliases": ["本地通知", "Notification", "NotificationRequest"],
        "intent": "发送应用内本地通知，包含标题、正文、角标。",
        "when_to_use": ["定时提醒", "任务完成通知", "下载完成提示"],
        "recommended_apis": ["arkui.notification"],
        "optional_apis": [],
        "path_keywords": ["NotificationKit", "publishNotification", "NotificationRequest"],
        "example_keywords": ["本地通知", "publish"],
        "tags": ["notification"],
    },
    {
        "task_id": "background.task.long_running",
        "title": "长时后台任务",
        "aliases": ["后台任务", "BackgroundTasks", "长时任务"],
        "intent": "申请长时后台任务，保证特定业务可在退后台继续执行。",
        "when_to_use": ["后台下载 / 上传", "后台播放音频", "后台定位"],
        "recommended_apis": ["harmonyos.background_tasks"],
        "optional_apis": [],
        "path_keywords": ["BackgroundTasksKit", "startBackgroundRunning"],
        "example_keywords": ["长时任务申请", "backgroundTaskManager"],
        "tags": ["background", "lifecycle"],
    },
    {
        "task_id": "security.biometric.auth",
        "title": "生物识别认证",
        "aliases": ["生物识别", "指纹", "人脸识别", "UserAuth"],
        "intent": "调起系统生物识别能力做本地鉴权。",
        "when_to_use": ["支付前二次认证", "敏感操作鉴权", "开启应用锁"],
        "recommended_apis": ["harmonyos.userauth"],
        "optional_apis": [],
        "path_keywords": ["UserAuthenticationKit", "userAuth", "BiometricAuth"],
        "example_keywords": ["用户认证示例", "auth.start"],
        "tags": ["security", "auth"],
    },
    {
        "task_id": "security.keystore.key",
        "title": "Keystore 密钥管理",
        "aliases": ["Keystore", "密钥存储", "HUKS"],
        "intent": "用 Keystore 生成、存储、使用密钥做加解密 / 签名。",
        "when_to_use": ["保护 token", "本地敏感数据加密", "签名 / 验签"],
        "recommended_apis": ["harmonyos.keystore"],
        "optional_apis": ["arkui.crypto_framework"],
        "path_keywords": ["UniversalKeystoreKit", "HUKS", "generateKeyItem"],
        "example_keywords": ["密钥生成", "huks.generateKeyItem"],
        "tags": ["security", "keystore"],
    },
    {
        "task_id": "security.token.secure_storage",
        "title": "Token 安全存储",
        "aliases": ["保存 token", "secure storage", "密文保存"],
        "intent": "结合 Keystore + Preferences，把鉴权 token 以密文形式存本地。",
        "when_to_use": ["登录态持久化", "敏感字符串入库"],
        "recommended_apis": ["harmonyos.keystore", "harmonyos.data.preferences"],
        "optional_apis": [],
        "path_keywords": ["UniversalKeystoreKit", "ohos_preferences"],
        "example_keywords": ["加密保存", "Keystore 加密"],
        "tags": ["security", "storage"],
    },
    {
        "task_id": "ui.toast.prompt",
        "title": "Toast 轻提示",
        "aliases": ["Toast", "showToast", "轻提示"],
        "intent": "用 promptAction 弹出短暂 Toast 提示。",
        "when_to_use": ["操作成功 / 失败反馈", "表单错误提示"],
        "recommended_apis": ["arkui.prompt_action"],
        "optional_apis": [],
        "path_keywords": ["cj-components-promptaction", "showToast"],
        "example_keywords": ["showToast", "Toast 示例"],
        "tags": ["ui", "prompt"],
    },
    {
        "task_id": "ui.loading.global",
        "title": "全局 Loading 遮罩",
        "aliases": ["全局 Loading", "loading 遮罩", "加载中"],
        "intent": "实现全屏加载遮罩 + 进度指示，常与请求耦合。",
        "when_to_use": ["请求阻塞 UI", "文件上传等待", "支付等待"],
        "recommended_apis": ["arkui.prompt_action", "arkui.progress"],
        "optional_apis": [],
        "path_keywords": ["cj-dialog-loadingdialog", "LoadingProgress", "promptAction"],
        "example_keywords": ["Loading 示例", "showDialog"],
        "tags": ["ui", "loading"],
    },
    {
        "task_id": "ui.actionmenu.longpress",
        "title": "长按弹出菜单",
        "aliases": ["ActionMenu", "长按菜单", "contextmenu"],
        "intent": "长按组件弹出操作菜单（删除 / 分享 / 收藏）。",
        "when_to_use": ["列表项长按", "聊天气泡操作"],
        "recommended_apis": ["arkui.prompt_action"],
        "optional_apis": ["arkui.list_item"],
        "path_keywords": ["cj-dialog-actionmenu", "showActionMenu"],
        "example_keywords": ["actionMenu 示例", "长按菜单"],
        "tags": ["ui", "menu"],
    },
    {
        "task_id": "ui.gesture.pan_pinch",
        "title": "手势识别（拖动 / 缩放）",
        "aliases": ["手势", "gesture", "PanGesture", "PinchGesture"],
        "intent": "监听 Pan / Pinch / LongPress / Tap 等手势组合。",
        "when_to_use": ["图片预览缩放", "拖拽排序", "自定义卡片拖动"],
        "recommended_apis": ["arkui.gesture"],
        "optional_apis": [],
        "path_keywords": ["cj-gesture-gestures", "gesture.Pan", "PinchGesture"],
        "example_keywords": ["手势示例", "onPan"],
        "tags": ["ui", "gesture"],
    },
    {
        "task_id": "ui.keyboard.avoid",
        "title": "软键盘避让布局",
        "aliases": ["键盘遮挡", "软键盘", "keyboard avoidance"],
        "intent": "当输入框被软键盘遮挡时自动上移布局。",
        "when_to_use": ["聊天输入框", "表单页面", "评论栏"],
        "recommended_apis": ["arkui.text_input"],
        "optional_apis": ["arkui.scroll"],
        "path_keywords": ["cj-components-textinput", "keyboardAvoidMode", "软键盘"],
        "example_keywords": ["避让键盘", "keyboard 示例"],
        "tags": ["ui", "keyboard"],
    },
    {
        "task_id": "ui.tabs.lazy",
        "title": "Tabs + 懒加载切页",
        "aliases": ["Tabs", "选项卡", "懒加载 Tab"],
        "intent": "用 Tabs 组件实现多页签切换，配合 LazyForEach 懒构建。",
        "when_to_use": ["首页多 Tab", "分类切换"],
        "recommended_apis": ["arkui.tabs", "arkui.lazyforeach"],
        "optional_apis": [],
        "path_keywords": ["cj-scroll-swipe-tabs", "Tabs", "TabContent"],
        "example_keywords": ["Tabs 示例", "Tab 切换"],
        "tags": ["ui", "tabs"],
    },
    {
        "task_id": "ui.sidebar.drawer",
        "title": "侧边抽屉",
        "aliases": ["SideBar", "抽屉", "Drawer", "sidebarcontainer"],
        "intent": "用 SideBarContainer 实现左右抽屉式导航。",
        "when_to_use": ["历史记录抽屉", "设置菜单", "分类筛选"],
        "recommended_apis": ["arkui.sidebar_container"],
        "optional_apis": ["arkui.navigation"],
        "path_keywords": ["cj-components-sidebarcontainer", "SideBarContainer"],
        "example_keywords": ["SideBar 示例", "侧边抽屉"],
        "tags": ["ui", "navigation"],
    },
    {
        "task_id": "ui.drag_drop.custom",
        "title": "拖拽与跨组件放下",
        "aliases": ["Drag Drop", "拖拽", "drag and drop"],
        "intent": "在组件间实现拖起 / 放下交互。",
        "when_to_use": ["列表重排序", "跨分区拖动", "拖图片到卡片"],
        "recommended_apis": ["arkui.drag_drop"],
        "optional_apis": [],
        "path_keywords": ["cj-drag-drop", "onDragStart", "onDrop"],
        "example_keywords": ["拖拽示例", "onDragEnter"],
        "tags": ["ui", "drag"],
    },
    {
        "task_id": "ui.canvas.draw",
        "title": "Canvas 自定义绘制",
        "aliases": ["Canvas", "自定义绘制", "画板"],
        "intent": "用 Canvas 的 2D 上下文自定义绘制图形。",
        "when_to_use": ["手写签名", "图表", "涂鸦画板"],
        "recommended_apis": ["arkui.canvas_context_2d"],
        "optional_apis": [],
        "path_keywords": ["cj-canvas", "CanvasRenderingContext2D"],
        "example_keywords": ["Canvas 示例", "ctx.fillRect"],
        "tags": ["ui", "canvas"],
    },
    {
        "task_id": "ui.responsive.mediaquery",
        "title": "响应式布局 MediaQuery",
        "aliases": ["响应式", "MediaQuery", "自适应布局"],
        "intent": "用 mediaquery 监听设备宽度 / 方向变化，动态切换布局。",
        "when_to_use": ["手机平板同应用", "横竖屏适配"],
        "recommended_apis": ["arkui.mediaquery"],
        "optional_apis": ["arkui.flex", "arkui.grid"],
        "path_keywords": ["cj-apis-mediaquery", "mediaquery.matchMediaSync"],
        "example_keywords": ["MediaQuery 示例", "matchMediaSync"],
        "tags": ["layout", "responsive"],
    },
    {
        "task_id": "ui.pip.window",
        "title": "画中画 PictureInPicture",
        "aliases": ["画中画", "PiP", "小窗"],
        "intent": "视频应用进入画中画小窗，退后台继续播放。",
        "when_to_use": ["视频播放器", "视频会议", "导航悬浮窗"],
        "recommended_apis": ["arkui.pipwindow"],
        "optional_apis": ["arkui.video"],
        "path_keywords": ["cj-apis-pipwindow", "PictureInPicture"],
        "example_keywords": ["画中画示例", "pipWindow.create"],
        "tags": ["ui", "window"],
    },
    {
        "task_id": "ui.window.multi",
        "title": "多窗口与子窗口",
        "aliases": ["多窗口", "子窗口", "WindowStage"],
        "intent": "管理应用主窗口 / 子窗口 / 悬浮窗。",
        "when_to_use": ["浮窗工具条", "分屏操作", "弹窗对话框"],
        "recommended_apis": ["harmonyos.window_manager"],
        "optional_apis": [],
        "path_keywords": ["cj-application-window-stage", "WindowStage", "windowManager"],
        "example_keywords": ["子窗口", "WindowStage 示例"],
        "tags": ["window"],
    },
    {
        "task_id": "ui.darkmode.adaptive",
        "title": "深色模式自适应",
        "aliases": ["深色模式", "夜间模式", "darkMode"],
        "intent": "让应用随系统深浅模式切换资源与颜色。",
        "when_to_use": ["适配系统深色模式", "自定义切换主题"],
        "recommended_apis": ["arkui.mediaquery"],
        "optional_apis": ["harmonyos.resource_manager"],
        "path_keywords": ["cj-ui-darkmode", "dark-mode", "resource.color"],
        "example_keywords": ["深色模式示例", "prefers-color-scheme"],
        "tags": ["ui", "theming"],
    },
    {
        "task_id": "i18n.localization.runtime",
        "title": "运行时国际化",
        "aliases": ["i18n", "国际化", "语言切换"],
        "intent": "用 Localization Kit 动态切换语言并刷新 UI。",
        "when_to_use": ["多语言应用", "地区格式化日期 / 货币"],
        "recommended_apis": ["harmonyos.localization"],
        "optional_apis": ["arkui.state"],
        "path_keywords": ["LocalizationKit", "intl", "I18n"],
        "example_keywords": ["国际化示例", "I18n.getSystemLanguage"],
        "tags": ["i18n"],
    },
    {
        "task_id": "navigation.notification_to_page",
        "title": "从通知跳转指定页面",
        "aliases": ["通知跳转", "want 跳转", "push 跳页"],
        "intent": "点击推送 / 本地通知后通过 Want 跳转到目标 Page。",
        "when_to_use": ["IM 消息点击进入会话", "营销通知跳详情"],
        "recommended_apis": ["harmonyos.ability_kit", "arkui.router"],
        "optional_apis": ["arkui.notification"],
        "path_keywords": ["AbilityKit", "startAbility", "Want"],
        "example_keywords": ["Want 示例", "startAbility"],
        "tags": ["navigation", "ability"],
    },
    {
        "task_id": "web.interop.jsbridge",
        "title": "WebView 与原生双向通信",
        "aliases": ["JSBridge", "registerJavaScriptProxy", "runJavaScript"],
        "intent": "让页面内 WebView 与原生代码通过 JSBridge 互相调用。",
        "when_to_use": ["H5 调原生能力", "原生通知 H5 刷新", "跨端容器"],
        "recommended_apis": ["arkui.web"],
        "optional_apis": ["arkui.prompt_action"],
        "path_keywords": ["cj-apis-webview", "registerJavaScriptProxy", "runJavaScript"],
        "example_keywords": ["JSBridge 示例", "registerJavaScriptProxy"],
        "tags": ["web", "interop"],
    },
    {
        "task_id": "web.intercept.request",
        "title": "WebView 拦截请求",
        "aliases": ["WebView 拦截", "interceptRequest", "自定义资源"],
        "intent": "拦截 WebView 发起的网络请求并替换响应 / 注入 header。",
        "when_to_use": ["离线缓存 H5 资源", "全局注入鉴权 header", "拦截 js / css"],
        "recommended_apis": ["arkui.web"],
        "optional_apis": [],
        "path_keywords": ["cj-apis-webview", "onInterceptRequest", "WebResourceResponse"],
        "example_keywords": ["拦截请求示例", "interceptRequest"],
        "tags": ["web"],
    },
    {
        "task_id": "performance.trace.analyze",
        "title": "性能分析 Trace",
        "aliases": ["性能分析", "hitrace", "Performance Analysis"],
        "intent": "用 HiTrace / Profile 工具分析耗时与帧率问题。",
        "when_to_use": ["启动慢排查", "滑动卡顿定位", "冷启动优化"],
        "recommended_apis": ["harmonyos.performance_analysis"],
        "optional_apis": [],
        "path_keywords": ["PerformanceAnalysisKit", "hitrace", "hiappevent"],
        "example_keywords": ["性能埋点", "hiTraceMeter"],
        "tags": ["performance", "profiling"],
    },
    {
        "task_id": "performance.list.virtualization",
        "title": "长列表性能优化",
        "aliases": ["列表性能", "滑动卡顿", "virtual list"],
        "intent": "用 LazyForEach + cachedCount + 复用组件优化长列表。",
        "when_to_use": ["万级数据列表", "滑动掉帧", "图片列表优化"],
        "recommended_apis": ["arkui.lazyforeach", "arkui.list"],
        "optional_apis": ["arkui.list_item_group"],
        "path_keywords": ["cj-scroll-swipe-lazyforeach", "cachedCount", "IDataSource"],
        "example_keywords": ["LazyForEach 示例", "cachedCount"],
        "tags": ["performance", "list"],
    },
    {
        "task_id": "lifecycle.ability.restore",
        "title": "Ability 状态保存与恢复",
        "aliases": ["状态保存", "onSaveState", "Ability 恢复"],
        "intent": "处理 Ability 被系统回收后状态的保存 / 恢复。",
        "when_to_use": ["后台杀回恢复场景", "异常恢复", "横竖屏旋转"],
        "recommended_apis": ["harmonyos.ability_kit"],
        "optional_apis": [],
        "path_keywords": ["AbilityKit", "onSaveState", "AbilityLifecycleState"],
        "example_keywords": ["状态保存", "onSaveState 示例"],
        "tags": ["lifecycle", "ability"],
    },
    {
        "task_id": "lifecycle.startup.preload",
        "title": "启动期预加载",
        "aliases": ["启动预加载", "冷启动", "preload"],
        "intent": "在 Ability / AppStartup 阶段预加载热路径数据。",
        "when_to_use": ["首屏数据预取", "字典 / 配置预加载", "缩短白屏时间"],
        "recommended_apis": ["harmonyos.ability_kit"],
        "optional_apis": ["harmonyos.app_startup"],
        "path_keywords": ["AbilityKit", "onCreate", "AppStartup"],
        "example_keywords": ["AppStartup 示例", "onCreate"],
        "tags": ["lifecycle", "startup"],
    },
    {
        "task_id": "permission.request.runtime",
        "title": "运行时权限申请",
        "aliases": ["权限申请", "requestPermissions", "授权弹窗"],
        "intent": "在运行时向用户申请敏感权限（相机 / 位置 / 通讯录）。",
        "when_to_use": ["首次用相机 / 定位", "申请麦克风权限", "联系人读取"],
        "recommended_apis": ["harmonyos.ability_kit"],
        "optional_apis": [],
        "path_keywords": ["AbilityKit", "requestPermissionsFromUser", "grantPermission"],
        "example_keywords": ["权限申请示例", "requestPermissionsFromUser"],
        "tags": ["permission"],
    },
    {
        "task_id": "share.to_other_app",
        "title": "分享到三方应用",
        "aliases": ["分享", "share", "ShareController"],
        "intent": "用 Want / Intent 把文本 / 图片分享到三方。",
        "when_to_use": ["分享文章 / 商品", "导出图片到相册", "跳三方打开文件"],
        "recommended_apis": ["harmonyos.ability_kit"],
        "optional_apis": [],
        "path_keywords": ["AbilityKit", "startAbility", "Want.Parameters"],
        "example_keywords": ["分享示例", "startAbility"],
        "tags": ["share", "ability"],
    },
    {
        "task_id": "payment.kit.basic",
        "title": "应用内支付",
        "aliases": ["支付", "Payment Kit", "IAP"],
        "intent": "接入 Payment Kit 完成订单支付。",
        "when_to_use": ["电商支付", "订阅收费", "道具购买"],
        "recommended_apis": ["harmonyos.payment"],
        "optional_apis": [],
        "path_keywords": ["PaymentKit", "createOrder", "requestPay"],
        "example_keywords": ["支付示例", "requestPay"],
        "tags": ["payment"],
    },
    {
        "task_id": "arkinterop.ts_call_cj",
        "title": "ArkTS 调用仓颉",
        "aliases": ["ArkTS 调用仓颉", "ts call cj", "跨语言调用"],
        "intent": "在 ArkTS 代码里调用仓颉侧暴露的方法。",
        "when_to_use": ["已有 ArkTS 项目接入仓颉模块", "渐进迁移"],
        "recommended_apis": ["arkui.arkts_interop"],
        "optional_apis": [],
        "path_keywords": ["arkinterop", "ArkTS 互操作", "@Interop"],
        "example_keywords": ["ArkTS 调用示例"],
        "tags": ["interop"],
    },
    {
        "task_id": "concurrency.coroutine.basic",
        "title": "仓颉协程并发",
        "aliases": ["协程", "coroutine", "spawn"],
        "intent": "用仓颉协程并发执行异步任务。",
        "when_to_use": ["并发请求", "并行计算", "异步 IO"],
        "recommended_apis": ["cangjie.concurrent"],
        "optional_apis": [],
        "path_keywords": ["concurrent", "spawn", "Future"],
        "example_keywords": ["协程示例", "spawn"],
        "tags": ["concurrency", "lang"],
    },
    {
        "task_id": "concurrency.channel.sync",
        "title": "Channel 线程间通信",
        "aliases": ["Channel", "线程通信", "ChannelSender"],
        "intent": "使用 Channel 在并发任务之间传递消息。",
        "when_to_use": ["协程同步", "生产者消费者模式", "跨线程事件"],
        "recommended_apis": ["cangjie.sync"],
        "optional_apis": [],
        "path_keywords": ["std/sync", "Channel", "Mutex"],
        "example_keywords": ["Channel 示例"],
        "tags": ["concurrency"],
    },
    {
        "task_id": "pattern.singleton.basic",
        "title": "仓颉单例模式",
        "aliases": ["单例", "singleton", "唯一实例"],
        "intent": "在仓颉里实现单例的线程安全写法。",
        "when_to_use": ["全局配置", "全局网络客户端", "全局 logger"],
        "recommended_apis": [],
        "optional_apis": ["cangjie.sync"],
        "path_keywords": ["lang-features/class", "package-management", "single instance"],
        "example_keywords": ["单例示例"],
        "tags": ["pattern", "lang"],
    },
    {
        "task_id": "diagnostics.hilog.trace",
        "title": "Hilog 日志输出",
        "aliases": ["Hilog", "日志", "log.debug"],
        "intent": "用 Hilog 输出带 tag / level 的应用日志。",
        "when_to_use": ["调试排错", "线上日志", "追踪请求"],
        "recommended_apis": ["harmonyos.hilog"],
        "optional_apis": [],
        "path_keywords": ["PerformanceAnalysisKit", "hilog", "HiLog"],
        "example_keywords": ["Hilog 示例", "hilog.info"],
        "tags": ["diagnostics", "log"],
    },
    {
        "task_id": "diagnostics.crash.handle",
        "title": "崩溃捕获与上报",
        "aliases": ["崩溃捕获", "crash", "错误上报"],
        "intent": "捕获应用崩溃并通过 hiAppEvent 上报。",
        "when_to_use": ["线上崩溃监控", "异常聚合"],
        "recommended_apis": ["harmonyos.hiappevent"],
        "optional_apis": ["harmonyos.hilog"],
        "path_keywords": ["hiappevent-watcher", "Watcher", "CrashEvent"],
        "example_keywords": ["崩溃捕获", "hiAppEvent"],
        "tags": ["diagnostics", "crash"],
    },
    {
        "task_id": "background.timer.schedule",
        "title": "定时任务调度",
        "aliases": ["定时任务", "timer", "schedule"],
        "intent": "用仓颉 std.time / WorkScheduler 等调度定时任务。",
        "when_to_use": ["心跳", "轮询", "延时重试", "后台统计"],
        "recommended_apis": ["std.time"],
        "optional_apis": ["harmonyos.work_scheduler"],
        "path_keywords": ["std/time", "WorkScheduler", "setTimeout"],
        "example_keywords": ["timer 示例"],
        "tags": ["background", "scheduler"],
    },
    {
        "task_id": "data.rdb.index",
        "title": "RDB 查询优化与索引",
        "aliases": ["RDB 索引", "数据库索引", "RelationalStore 优化"],
        "intent": "给 RelationalStore 的表建索引并优化慢查询。",
        "when_to_use": ["表过大查询慢", "常用字段查询优化"],
        "recommended_apis": ["harmonyos.relational_store"],
        "optional_apis": [],
        "path_keywords": ["ohos_relationalstore", "executeSql", "CREATE INDEX"],
        "example_keywords": ["RDB 索引示例", "createIndex"],
        "tags": ["data", "rdb", "performance"],
    },
    {
        "task_id": "data.rdb.transaction",
        "title": "RDB 事务",
        "aliases": ["数据库事务", "transaction", "beginTransaction"],
        "intent": "在 RelationalStore 中使用事务保证一致性。",
        "when_to_use": ["批量写入", "钱款类双边更新", "回滚出错操作"],
        "recommended_apis": ["harmonyos.relational_store"],
        "optional_apis": [],
        "path_keywords": ["ohos_relationalstore", "beginTransaction", "commit"],
        "example_keywords": ["事务示例"],
        "tags": ["data", "rdb"],
    },
    {
        "task_id": "ui.anim.theme_transition",
        "title": "主题切换动画",
        "aliases": ["主题切换动画", "夜间模式切换", "theme transition"],
        "intent": "切换深浅模式 / 主题时加过渡动画。",
        "when_to_use": ["深色模式切换", "皮肤切换"],
        "recommended_apis": ["arkui.animation"],
        "optional_apis": ["arkui.mediaquery"],
        "path_keywords": ["cj-animation", "animateTo", "transition"],
        "example_keywords": ["主题切换动画"],
        "tags": ["animation", "theming"],
    },
    {
        "task_id": "ui.form.validation",
        "title": "表单校验",
        "aliases": ["表单校验", "form validation", "错误提示"],
        "intent": "校验 TextInput / 表单字段，错误时高亮并提示。",
        "when_to_use": ["注册 / 登录表单", "实名信息校验"],
        "recommended_apis": ["arkui.text_input", "arkui.prompt_action"],
        "optional_apis": [],
        "path_keywords": ["cj-components-textinput", "validation"],
        "example_keywords": ["表单校验示例"],
        "tags": ["ui", "form"],
    },
    {
        "task_id": "ui.bg_blur.effect",
        "title": "背景模糊效果",
        "aliases": ["背景模糊", "BackgroundBlur", "毛玻璃"],
        "intent": "给组件或弹窗背景应用 blur 效果。",
        "when_to_use": ["弹窗背景模糊", "磨砂卡片", "沉浸式背景"],
        "recommended_apis": ["arkui.animation"],
        "optional_apis": [],
        "path_keywords": ["cj-universal-attribute-background", "backgroundBlurStyle"],
        "example_keywords": ["背景模糊示例"],
        "tags": ["ui", "visual_effect"],
    },
]
